### ISSUE TITLE
Check swagger format field before x-chance-type

### ISSUE THREAD

**Issue by blockloop** [dzdrazil/swagger-mock-api#14]
The `format` field is defined by the [Swagger spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types) as "free form." Instead of relying directly on the x-chance-type you could check the `format` property first. For example:

``` yaml
    properties:
      name:
        type: string
        format: name
      birthDate:
        type: string
        format: date-time
      token:
        type: string
        format: uuid
      emailAddress:
        type: string
        format: email
      address:
        type: string
        format: address
      someOutlier:
        type: string
        x-chance-type: <whatever you want>
```

In outlier cases the `x-chance-type` could be supplied, but for most of the API I just documented the `format` property would suffice. This keeps from muddying up the spec.
